
spring:
  datasource:
    password : 07910506
    url : jdbc:mysql://localhost:3306/lost_petdb
    username : root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
