export class Product{
  abs : boolean;
  active_ads : any;
  airbags : number;
  alarm : boolean;
  auction : boolean;
  auction_has_key : number;
  back_camera : boolean;
  board_comp : boolean;
  car_desc : string;
  car_id : number;
  car_model : string;
  car_run : number;
  car_run_dim : number;
  car_run_km : number;
  category_id : number;
  central_lock : boolean;
  chair_warming : boolean;
  changable : boolean;
  checked : boolean;
  checked_for_duplicates : boolean;
  client_name : string;
  client_phone : number;
  climat_control : boolean;
  color_id : number;
  comfort_features : number[];
  condition_type_id : number;
  conditioner : boolean;
  currency_id : number;
  customs_passed : boolean;
  cylinder : number;
  dealerId : any;
  dealer_title : any;
  dealer_user_id : number;
  disks : boolean;
  door_type_id : number;
  drive_type_id : number;
  el_starter : number;
  el_windows : number;
  engine_volume : number;
  esd:boolean;
  first_deposit : number;
  for_rent : boolean;
  fuel_type_id : number;
  gear_type_id : number;
  has_catalyst : number;
  has_logo : any;
  has_predicted_price : boolean;
  has_turbo : boolean;
  hatch : boolean;
  hdd : number;
  hours_used : number;
  hp : number;
  hydraulics : boolean;
  inspected_in_greenway : boolean;
  is_auction : number;
  is_payd : boolean;
  lang_type_id : number;
  leather : boolean;
  license_number : string;
  location_id : number;
  logo_ver : any;
  man_id : number;
  map_lat:number;
  map_long : number;
  map_title : string;
  model_id : number;
  nav_system : boolean;
  obstacle_indicator : boolean;
  order_date : string;
  order_number : number;
  paid_add : number;
  parent_loc_id : number;
  photo : string;
  photo_ver : number;
  pic_number : number;
  pred_first_breakpoint : number;
  pred_max_price : number;
  pred_min_price : number;
  pred_second_breakpoint : number;
  predicted_price : number;
  price : number;
  price_usd : number;
  price_value : number;
  primary_damage_type : number;
  prod_month : number;
  prod_year : number;
  prom_color : number;
  rent_daily : boolean;
  rent_driver : boolean;
  rent_insured : boolean;
  rent_purchase : boolean;
  right_wheel : boolean;
  saloon_color_id : number;
  saloon_material_id : number;
  secondary_damage_type : number;
  special_persons : boolean;
  start_stop:boolean;
  status_id : number;
  stickers : any;
  tech_inspection : boolean;
  tmp : string;
  trunk : boolean;
  user_id : number;
  user_type : any;
  vehicle_type : number;
  video_url : string;
  views : number;
  vin : string;
  windshield : boolean;
  words_checked : number;
  zoom : number;
  constructor(abs : boolean,
    active_ads : any,
    airbags : number,
    alarm : boolean,
    auction : boolean,
    auction_has_key : number,
    back_camera : boolean,
    board_comp : boolean,
    car_desc : string,
    car_id : number,
    car_model : string,
    car_run : number,
    car_run_dim : number,
    car_run_km : number,
    category_id : number,
    central_lock : boolean,
    chair_warming : boolean,
    changable : boolean,
    checked : boolean,
    checked_for_duplicates : boolean,
    client_name : string,
    client_phone : number,
    climat_control : boolean,
    color_id : number,
    comfort_features : number[],
    condition_type_id : number,
    conditioner : boolean,
    currency_id : number,
    customs_passed : boolean,
    cylinder : number,
    dealerId : any,
    dealer_title : any,
    dealer_user_id : number,
    disks : boolean,
    door_type_id : number,
    drive_type_id : number,
    el_starter : number,
    el_windows : number,
    engine_volume : number,
    esd:boolean,
    first_deposit : number,
    for_rent : boolean,
    fuel_type_id : number,
    gear_type_id : number,
    has_catalyst : number,
    has_logo : any,
    has_predicted_price : boolean,
    has_turbo : boolean,
    hatch : boolean,
    hdd : number,
    hours_used : number,
    hp : number,
    hydraulics : boolean,
    inspected_in_greenway : boolean,
    is_auction : number,
    is_payd : boolean,
    lang_type_id : number,
    leather : boolean,
    license_number : string,
    location_id : number,
    logo_ver : any,
    man_id : number,
    map_lat:number,
    map_long : number,
    map_title : string,
    model_id : number,
    nav_system : boolean,
    obstacle_indicator : boolean,
    order_date : string,
    order_number : number,
    paid_add : number,
    parent_loc_id : number,
    photo : string,
    photo_ver : number,
    pic_number : number,
    pred_first_breakpoint : number,
    pred_max_price : number,
    pred_min_price : number,
    pred_second_breakpoint : number,
    predicted_price : number,
    price : number,
    price_usd : number,
    price_value : number,
    primary_damage_type : number,
    prod_month : number,
    prod_year : number,
    prom_color : number,
    rent_daily : boolean,
    rent_driver : boolean,
    rent_insured : boolean,
    rent_purchase : boolean,
    right_wheel : boolean,
    saloon_color_id : number,
    saloon_material_id : number,
    secondary_damage_type : number,
    special_persons : boolean,
    start_stop:boolean,
    status_id : number,
    stickers : any,
    tech_inspection : boolean,
    tmp : string,
    trunk : boolean,
    user_id : number,
    user_type : any,
    vehicle_type : number,
    video_url : string,
    views : number,
    vin : string,
    windshield : boolean,
    words_checked : number,
    zoom : number,){
      this.abs = abs;
    this.active_ads = active_ads;
    this.airbags = airbags;
    this.alarm = alarm;
    this.auction = auction;
    this.auction_has_key = auction_has_key;
    this.back_camera = back_camera;
    this.board_comp = board_comp;
    this.car_desc = car_desc;
    this.car_id = car_id;
    this.car_model = car_model;
    this.car_run = car_run;
    this.car_run_dim = car_run_dim;
    this.car_run_km = car_run_km;
    this.category_id = category_id;
    this.central_lock = central_lock;
    this.chair_warming = chair_warming;
    this.changable = changable;
    this.checked = checked;
    this.checked_for_duplicates = checked_for_duplicates;
    this.client_name = client_name;
    this.client_phone = client_phone;
    this.climat_control = climat_control;
    this.color_id = color_id;
    this.comfort_features = comfort_features;
    this.condition_type_id = condition_type_id;
    this.conditioner = conditioner;
    this.currency_id = currency_id;
    this.customs_passed = customs_passed;
    this.cylinder = cylinder;
    this.dealerId = dealerId;
    this.dealer_title = dealer_title;
    this.dealer_user_id = dealer_user_id;
    this.disks = disks;
    this.door_type_id = door_type_id;
    this.drive_type_id = drive_type_id;
    this.el_starter = el_starter;
    this.el_windows = el_windows;
    this.engine_volume = engine_volume;
    this.esd = esd;
    this.first_deposit = first_deposit;
    this.for_rent = for_rent;
    this.fuel_type_id = fuel_type_id;
    this.gear_type_id = gear_type_id;
    this.has_catalyst = has_catalyst;
    this.has_logo = has_logo;
    this.has_predicted_price = has_predicted_price;
    this.has_turbo = has_turbo;
    this.hatch = hatch;
    this.hdd = hdd;
    this.hours_used = hours_used;
    this.hp = hp;
    this.hydraulics = hydraulics;
    this.inspected_in_greenway = inspected_in_greenway;
    this.is_auction = is_auction;
    this.is_payd = is_payd;
    this.lang_type_id = lang_type_id;
    this.leather = leather;
    this.license_number = license_number;
    this.location_id = location_id;
    this.logo_ver = logo_ver;
    this.man_id = man_id;
    this.map_lat = map_lat;
    this.map_long = map_long;
    this.map_title = map_title;
    this.model_id = model_id;
    this.nav_system = nav_system;
    this.obstacle_indicator = obstacle_indicator;
    this.order_date = order_date;
    this.order_number = order_number;
    this.paid_add = paid_add;
    this.parent_loc_id = parent_loc_id;
    this.photo = photo;
    this.photo_ver = photo_ver;
    this.pic_number = pic_number;
    this.pred_first_breakpoint = pred_first_breakpoint;
    this.pred_max_price = pred_max_price;
    this.pred_min_price = pred_min_price;
    this.pred_second_breakpoint = pred_second_breakpoint;
    this.predicted_price = predicted_price;
    this.price = price;
    this.price_usd = price_usd;
    this.price_value = price_value;
    this.primary_damage_type = primary_damage_type;
    this.prod_month = prod_month;
    this.prod_year = prod_year;
    this.prom_color = prom_color;
    this.rent_daily = rent_daily;
    this.rent_driver = rent_driver;
    this.rent_insured = rent_insured;
    this.rent_purchase = rent_purchase;
    this.right_wheel = right_wheel;
    this.saloon_color_id = saloon_color_id;
    this.saloon_material_id = saloon_material_id;
    this.secondary_damage_type = secondary_damage_type;
    this.special_persons = special_persons;
    this.start_stop = start_stop;
    this.status_id = status_id;
    this.stickers = stickers;
    this.tech_inspection = tech_inspection;
    this.tmp = tmp;
    this.trunk = trunk;
    this.user_id = user_id;
    this.user_type = user_type;
    this.vehicle_type = vehicle_type;
    this.video_url = video_url;
    this.views = views;
    this.vin = vin;
    this.windshield = windshield;
    this.words_checked = words_checked;
    this.zoom = zoom;
    }
    
}